dependencies:
- name: influxdb
  version: 0.2.1
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: mysql
  version: 0.2.4
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: kafka
  version: 0.2.0
  repository: http://monasca.io/monasca-helm/
- name: storm
  version: 0.4.0
  repository: http://monasca.io/monasca-helm/
